server:
    port: 8082
    contextPath: /Jpa-Hibernate
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/hibernate
        username: root
        password: 6731
        driver-class-name: com.mysql.cj.jdbc.Driver
